services:
  postgres_db:
    image: postgres:15
    container_name: population_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${APP_CONFIG__DB__POSTGRES_USER}"
      POSTGRES_PASSWORD: "${APP_CONFIG__DB__POSTGRES_PASSWORD}"
      POSTGRES_DB: "${APP_CONFIG__DB__POSTGRES_DB}"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${APP_CONFIG__DB__POSTGRES_USER} -d ${APP_CONFIG__DB__POSTGRES_DB}" ]
      timeout: 5s
      interval: 10s
      retries: 5
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  get_data:
    build: .
    container_name: get_data_service
    env_file:
      - .env
    depends_on:
      postgres_db:
        condition: service_healthy
#    command: poetry run python src/get_data.py


volumes:
  postgres_data: